import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './Providers/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CGV IPH',
  description: 'Generated by tuon',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <p className='text-4xl'>WTF</p>
          {children}
        </Providers>
        </body>
    </html>
  )
}
